language: groovy
rvm:
- 1.8.8
install:
- ant install-ivy -DfailIvy=false
before_script:
- export BUILD_LIFE=${TRAVIS_COMMIT:0:7}
script:
- ant -DbuildLife=${BUILD_LIFE}
jdk:
- openjdk9
notifications:
  slack:
    secure: rDlBNXG1nxlD06IKNNLJ3XTh65OPArhTGWNK3oRI5b893I2Lybab135bhBCG7SXgbUuoMuOsJOfxFAgOqt50l1fqabCFr79CowigVUhCBQLjln50fhiwcDKw2Ob6S8I0ctL1JbJd0VDtXDXjfzEW9VmqYDIZn4JTs0sJZ/VJIVBr5VaUWnttvhKASFXznffnLijVjCJw4ih/uVSJOCLsQDKcVURrmb992eWVbZXSFyDkI1CHWFD0jCqLlx2OL7gkHtXBR9V6u3YM+BNpJ1jsWlrSjPDzkC03naF1Uq+0vgYzXsV5dM5oR1oH/8xA+WJUt7ILH5dvGqYkAJwaSpqzPYVhX4BN2GO+F3qvxnxBssTu/hAnwzej5A/CoqgcWo4BtVhSm6Yi5chpZWUjkoI+e3JaTYnkdhfINuWnHtTkqK6HLT2KWQ7o5VUooWYwYXoDQ6bOM0aTbUgmMiXHjG6GFRkjxDDCGpwznOBWRmJe1e0Wfh2GIw6woBLBgIw+rRHhnJsIsjpus2G/KD6T9rImkWS1vfgVRULLnDIwVFg40MHOESh4YnxFOhL18Iy/R73lupSfH5sQQNHUGRhrsBwF0Xm9wcL/S9q+otP9yYzrexGp5gVebic1feOJgUgT/pmYGeLGH5D+fRfVg2aGavBamyv0/DznOO8kBmn1IgFMgCA=
    on_success: change
    on_failure: change
  email: false
deploy:
  provider: releases
  api_key:
    secure: KcBpkFaes74KGMm8X/rRA8e13+t3PmkefsAvOAR+iF4g1GyuLSPkP92Fb9vFfsXBph+qmFh5rNa2lIRf/3RXW6COxY7CMMaARxUfJOKE0rmIwF0qfKI+RZDh6abg92iYngunMZVN8WVft6Lv9ZTOYCWxr1Zs1Ll/Rl4PfvHNd1g=
  file_glob: true
  file: releases/*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: UrbanCode/Informatica-UCD
