language: groovy
rvm:
- 1.8.8
install:
- ant install-ivy -DfailIvy=false
before_script:
- export BUILD_LIFE=${TRAVIS_COMMIT:0:7}
script:
- ant -DbuildLife=${BUILD_LIFE}
jdk:
- openjdk9
notifications:
  slack:
    secure: rDlBNXG1nxlD06IKNNLJ3XTh65OPArhTGWNK3oRI5b893I2Lybab135bhBCG7SXgbUuoMuOsJOfxFAgOqt50l1fqabCFr79CowigVUhCBQLjln50fhiwcDKw2Ob6S8I0ctL1JbJd0VDtXDXjfzEW9VmqYDIZn4JTs0sJZ/VJIVBr5VaUWnttvhKASFXznffnLijVjCJw4ih/uVSJOCLsQDKcVURrmb992eWVbZXSFyDkI1CHWFD0jCqLlx2OL7gkHtXBR9V6u3YM+BNpJ1jsWlrSjPDzkC03naF1Uq+0vgYzXsV5dM5oR1oH/8xA+WJUt7ILH5dvGqYkAJwaSpqzPYVhX4BN2GO+F3qvxnxBssTu/hAnwzej5A/CoqgcWo4BtVhSm6Yi5chpZWUjkoI+e3JaTYnkdhfINuWnHtTkqK6HLT2KWQ7o5VUooWYwYXoDQ6bOM0aTbUgmMiXHjG6GFRkjxDDCGpwznOBWRmJe1e0Wfh2GIw6woBLBgIw+rRHhnJsIsjpus2G/KD6T9rImkWS1vfgVRULLnDIwVFg40MHOESh4YnxFOhL18Iy/R73lupSfH5sQQNHUGRhrsBwF0Xm9wcL/S9q+otP9yYzrexGp5gVebic1feOJgUgT/pmYGeLGH5D+fRfVg2aGavBamyv0/DznOO8kBmn1IgFMgCA=
    on_success: change
    on_failure: change
  email: false
deploy:
  provider: releases
  api_key:
    secure: eMrIONz4ebkuL6/pUfOFWsc6f394+GdY9qNoSBK55tCiFN4T+1dwdzd5EwBTFCZpD64j2+VGcr/lLtBzPmXc2nSK9sLvRdxvwxtTVZVGl7Z/QbTEJ68MFegJoJYRrTdnnMa0s/78TGfZZ4uoxr8KrYGtaRBRsz9yynN32xHeUy2JBTHpZbeKpFoN8dXc0j0Lf26khhkd1iYM3ca+YSkU875DrEfTI3y+HOXcfNgN715PawM4w5QUI5QBX5TwyQ/sy6GytgVLwCZYAf6Jlb/W2z4cVSLXSBfoM66PK0ffsGbXpLLfxTmK/ZVxdsc6+SoRd7viOYj+/hC5ttTcy/GAxdVKWBSp//qqwCBaL4cVE40z32I3HhLwqSCeutBWVTyqD9IL6xIddc3ERPGty189mXo2hIj9v+PJe8LfWzz3ZHGxCL0rqNrE9atv9gR+6j7xKkqSV0nEURupmS/ypRlyfPWY4/pMstnLEeTcthuiFvIhgNSZNR7nwNVzIWqAuCXTM6Aolui2vxUW0ls7t0xy+FXpYr1ev/eUnQQdwwkR5T3GR018fnN1X87MlW1eYaNK6wsbjT+o6soHmH6eLvU1H+JnPpcNeec5G5T/PFTLnIeJBPiKbG2iOpcaZ623MhbeamU849v/WlpZUSlawQrwowJpYMy052sXr+BcspExEEs=  file_glob: true
  file: releases/*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: UrbanCode/Informatica-UCD






